# Generated by Django 4.1 on 2022-08-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_code', models.CharField(max_length=255, verbose_name='action_name')),
                ('tel_on', models.BooleanField(verbose_name='tel_on-off')),
                ('tel_message', models.CharField(max_length=255, verbose_name='tel--message')),
                ('mail_on', models.BooleanField(verbose_name='mail_on-off')),
                ('mail_message', models.CharField(max_length=255, verbose_name='mail--message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name_plural': 'ActionCode',
                'db_table': 'action_code',
                'managed': True,
            },
        ),
    ]
