# Generated by Django 4.1 on 2022-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actioncode',
            name='tel_list',
            field=models.CharField(default='', max_length=255, verbose_name='tel-list'),
        ),
        migrations.AlterField(
            model_name='actioncode',
            name='tel_message',
            field=models.CharField(max_length=255, verbose_name='tel-message'),
        ),
    ]
